Only show preferred version of custom resources
vmware-tanzu/octant pull request #1737
Opened 2020-12-14 20:15 UTC by bryanl

Signed-off-by: bryanl <bryanliles@gmail.com>

**What this PR does / why we need it**:

When a CRD has multiple defined versions, they are all shown. This is
distracting and confusing for Octant users. Instead, only show the
preferred version, and if multiple versions exist, show them in the
summary for a custom resource.

<img width="1470" alt="Screen Shot 2020-12-14 at 3 15 05 PM" src="https://user-images.githubusercontent.com/240/102130747-36d88580-3e1f-11eb-9ea2-6df39754d8db.png">
<img width="1470" alt="Screen Shot 2020-12-14 at 3 15 20 PM" src="https://user-images.githubusercontent.com/240/102130754-39d37600-3e1f-11eb-98ee-c77478a99584.png">

**Which issue(s) this PR fixes**
- Fixes #1715

**Release note**:
```
Only show preferred version of custom resources```

2020-12-15 21:22 UTC, wwitzel3 approved these changes

2020-12-15 21:23 UTC, wwitzel3 commented
This looks good to me, @GuessWhoSamFoo if you have a moment to try it out, I'd like your feedback here as well.

2020-12-16 16:25 UTC, wwitzel3 requested changes
Sorry, I missed a thing, can you add a changelog entry for this. Thank you.

2020-12-16 17:05 UTC, GuessWhoSamFoo commented
Something weird happened on the rebase, but the core changes look fine to me.

2020-12-16 18:37 UTC, wwitzel3 approved these changes

2020-12-16 18:41 UTC, merged