Add storage class
vmware-tanzu/octant pull request #2059
Opened 2021-02-22 12:37 UTC by kaitoii11

Signed-off-by: kaitoii11 <kaitoii1111@gmail.com>

**What this PR does / why we need it**:
Add support for storage classes under Cluster -> Storage section/

**Which issue(s) this PR fixes**
- Fixes #1794 

**Special notes for your reviewer**:

**Release note**:
```
Add support for storageClasses
```

2021-02-23 21:52 UTC, GuessWhoSamFoo requested changes
This looks really good besides a new pieces of missing metadata. It'd also be helpful if you add a changelog entry to `changelogs/unreleased`

2021-02-23 21:52 UTC, GuessWhoSamFoo commented on internal/printer/storageclass.go
> +func (scc *StorageClassConfiguration) Create(options Options) (*component.Summary, error) {
The following configurations are missing (see https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource):
 - `allowVolumeExpansion`
 - `mountOptions`
 - `parameters`

2021-02-24 16:18 UTC, wwitzel3 approved these changes

2021-02-24 19:46 UTC, GuessWhoSamFoo requested changes

2021-02-24 19:46 UTC, GuessWhoSamFoo commented on internal/printer/storageclass.go
> +	for key, value := range sc.Parameters {
`sc.Parameters` is typed `map[string]string` so range does not loop through them deterministically.

This can be fixed via `table.Sort("Key")`

2021-02-25 17:31 UTC, GuessWhoSamFoo approved these changes
lgtm

2021-02-25 17:31 UTC, merged