Fixed issue with clusterless configuration
vmware-tanzu/octant pull request #2061
Opened 2021-02-22 23:59 UTC by mklanjsek

After recent dash refactor, we lost ability to run with `--disable-cluster-overview` option. Added extra checks to  prevent the Panic error and verified that fixed the issue.

Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

**Which issue(s) this PR fixes**
- Fixes #2058

2021-02-24 16:50 UTC, GuessWhoSamFoo requested changes
The root cause is missing `kubeconfig.Noop` functions missing in `pkg/dash/dash.go`

2021-02-26 01:08 UTC, mklanjsek commented
Excellent point, Sam - totally missed that. Added `Noop` kubeConfig option to both `WithoutClusterOverview` and `WithOpenCensus` helpers.  Decided to keep nil checks since they are valid checks.

2021-02-26 15:01 UTC, wwitzel3 approved these changes

2021-02-26 15:47 UTC, GuessWhoSamFoo approved these changes
lgtm

2021-02-26 15:48 UTC, merged