Refactor DynamicCache
vmware-tanzu/octant pull request #2144
Opened 2021-03-13 16:01 UTC by wwitzel3

**What this PR does / why we need it**:
This attempts to to all of the learning from HasAccess, SubjectAccess, current DynamicCache, and the InMemoryStore and refactor our existing DynamicCache implementation in a way that greatly improves performance and addresses our issues with attempting to access resources in cluster we don't have permissions for.

- [ ] Investigate dash_test.go (might not matter with @GuessWhoSamFoo refactors?)
- [ ] Write tests for new functionality

This also fixes the API inconsistencies

**Which issue(s) this PR fixes**
- Fixes #1526

2021-03-13 20:26 UTC, wwitzel3 commented
@scothis I'm interested to know if this refactor makes your CPU issue on macOS same / worse / no-change. If you get a chance to build this from the branch and try it out, that would be super helpful.

2021-03-15 14:15 UTC, scothis commented
@wwitzel3 new stats:

from master `bcdc1620`:
- browser open ~70%
- browser closed ~0.3%

from this pr `471b064d`:
- browser open ~70%
- browser closed ~0.8%

2021-03-19 14:41 UTC, mklanjsek requested changes
Tested a

2021-03-19 14:55 UTC, mklanjsek commented
Here is the console output:
```
2021-03-19T08:21:06.813-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for projectcontour.io/v1, Resource=httpproxies	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.813-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for tekton.dev/v1beta1, Resource=pipelines	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.813-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for caching.internal.knative.dev/v1alpha1, Resource=images	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.813-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for networking.internal.knative.dev/v1alpha1, Resource=ingresses	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for contour.heptio.com/v1beta1, Resource=ingressroutes	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for services.manage.tanzu.vmware.com/v1alpha1, Resource=inspections	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for intents.tmc.cloud.vmware.com/v1alpha1, Resource=inspects	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for cert-manager.io/v1alpha2, Resource=issuers	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for controlplane.cluster.x-k8s.io/v1alpha3, Resource=kubeadmcontrolplanes	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for flows.knative.dev/v1, Resource=sequences	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for sources.knative.dev/v1, Resource=sinkbindings	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for messaging.knative.dev/v1, Resource=subscriptions	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for tekton.dev/v1beta1, Resource=taskruns	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for tekton.dev/v1beta1, Resource=tasks	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for eventing.knative.dev/v1, Resource=triggers	{"component": "websocket-client", "client-id": "5647bbf4-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "e6477d6e-b359-40c3-b053-a3ece32af78b", "dynamicCache": "forResource"}
2021-03-19T08:21:06.814-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for intents.tmc.cloud.vmware.com/v1alpha1, Resource=loguploads	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for cluster.x-k8s.io/v1alpha3, Resource=machinehealthchecks	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for exp.cluster.x-k8s.io/v1alpha3, Resource=machinepools	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for intents.tmc.cloud.vmware.com/v1alpha1, Resource=managedimagepolicies	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for intents.tmc.cloud.vmware.com/v1alpha1, Resource=managednetworkpolicies{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for autoscaling.internal.knative.dev/v1alpha1, Resource=metrics	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for intents.tmc.cloud.vmware.com/v1alpha1, Resource=namespaceaccesspolicies{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d-a46e-646263eff16e", "dynamicCache": "forResource"}
2021-03-19T08:21:06.815-0600	INFO	objectstore/dynamic_cache.go:367	starting informer for insight.tmc.cloud.vmware.com/v1alpha1, Resource=opaviolations	{"component": "websocket-client", "client-id": "552b07c6-88be-11eb-9eaa-acde48001122", "poller-name": "navigation", "poller-instance": "8ed50d75-9d64-415d [...]

2021-03-23 18:38 UTC, mklanjsek approved these changes
Looks good, don't forget to squash commits!

2021-03-23 23:39 UTC, merged