Allow validator to set constraints
vmware-tanzu/octant pull request #2166
Opened 2021-03-16 20:33 UTC by lenriquez

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**
- Fixes #2017

**Special notes for your reviewer**:
This PR allows to use all this validations but the last two
https://angular.io/api/forms/Validators

**Release note**:
```
release-note
```

2021-03-16 20:34 UTC, lenriquez commented
@GuessWhoSamFoo Can you please help with this review?

2021-03-18 16:05 UTC, wwitzel3 commented
Does this actually change the existing behavior in anyway? This seems like it just changes the data format.

2021-03-18 16:21 UTC, GuessWhoSamFoo commented
This allows validators like `min`, `max`, `pattern`. Typed strings can be used here to be more discoverable with what types of validation is available.

2021-03-18 16:31 UTC, wwitzel3 commented
Got it now, ok, yeah, I was just using the default validation for required and I was like, this seems the same, but now I get it. I think using Typed strings to expose the validation types is a great idea.

2021-03-19 15:57 UTC, GuessWhoSamFoo requested changes

2021-03-21 21:04 UTC, lenriquez commented on web/src/app/modules/shared/components/presentation/form/form.component.ts
> +      if (value === '') {
I added checks for it, unfortunately every validation require at least one parameter, so I have to create a hash to check 
![image](https://user-images.githubusercontent.com/6991432/111920781-e8aad200-8a5e-11eb-906d-761f9dbe7922.png)

2021-03-21 21:04 UTC, lenriquez commented on web/src/app/modules/shared/components/presentation/form/form.component.ts
> +      if (value === '') {
![image](https://user-images.githubusercontent.com/6991432/111920806-0841fa80-8a5f-11eb-948f-f3703a66bcba.png)

2021-03-24 13:20 UTC, wwitzel3 approved these changes
LGTM, want to make sure @GuessWhoSamFoo is happy with it.

2021-03-24 16:05 UTC, GuessWhoSamFoo approved these changes
looks good - we need to remember this is a breaking API change and mark it as such in the changelog when releasing

2021-03-24 16:05 UTC, merged