Overhaul of Octant storybook implementation
vmware-tanzu/octant pull request #2386
Opened 2021-04-29 22:16 UTC by mklanjsek

The intention of this work was to provide better performance of our Storybook portal by using the newly released Storybook inline mode for angular components. However, it turned out that much more serious surgery was required to make everything working at that level, resulting in pretty much overhaul of internal Storybook organization.

- Bumped Storybook to latest 6.3 build
- Switched to inline story mode, so stories are now not displayed in iFrame, resulting in much better update performance. This required a few small fixes in our code base
- Modified each story to stop using the old `storiesOff` model and use the hoisted annotations
- Upgraded the component properties editing by replacing soon to be removed `knobs` addon (has issues with inline stories) with the new generation `controls` addon that supports editing in both Docs and Canvas mode
- Added the Accessibility pane so we can start keeping an eye on component accessibility
- Lots of small tweaks and improvements

2021-05-01 00:45 UTC, GuessWhoSamFoo commented
The deploy preview is failing because this needs a rebase to include the nelify.toml move from eb94d630b1b89b1e6e760f8005427b3d651ccbdb

2021-05-04 03:04 UTC, GuessWhoSamFoo requested changes

2021-05-04 17:54 UTC, mklanjsek commented on web/src/stories/graph.stories.ts
> +export default {
Good point, `Other/Resources` was double entry, it's fixed now.

2021-05-04 17:54 UTC, mklanjsek commented on web/src/stories/timeline.stories.mdx
> +        buttonGroup: buttonGroupView,
Updated button definition

2021-05-04 17:55 UTC, mklanjsek commented on web/src/stories/accordion.stories.mdx
> +         component={AccordionComponent}
You are right, I missed that. All Component entries are now removed from MDX stories.

2021-05-04 17:56 UTC, mklanjsek commented
@GuessWhoSamFoo PTAL

2021-05-04 19:07 UTC, GuessWhoSamFoo approved these changes
We are still seeing warnings for `storyFn` at 6.3: https://github.com/storybookjs/storybook/issues/13074

Not a blocker, but something to watch when storybook 7 comes out.

2021-05-04 19:33 UTC, mklanjsek commented
Sounds good, I am not seeing these but will keep an eye on them.

2021-05-04 19:35 UTC, merged