Added properties pane to Resource Viewer
vmware-tanzu/octant pull request #2481
Opened 2021-05-20 20:37 UTC by mklanjsek

Properties are now displayed for selected node in Resource Viewer: 

![Screen Shot 2021-05-20 at 2 20 39 PM](https://user-images.githubusercontent.com/34245594/119044021-ea1d4b80-b976-11eb-9c35-85f60856752e.png)

Properties are created and merged together like this:
1. `Version` and `Kind` are always present at the top. These were already passed down to client, so they are simply just directly added there,
2. `Namespace`, `Created` and `Labels` (if present) are added for all resource types,
3. Next group depends on resource type, for example for Pods we are adding `Service Account`, `Node` and `Controlled By` fields,
4. Lastly, at the very bottom are properties that are added by plugins. In screenshot above, you can see that our sample plugin has added the `ID` field (example how to do that is included for plugin authors),

**Special notes for your reviewer**:
Please let me know if there are certain properties that are better suited for a specific resource. We may need a second pass to tweak what exactly shows up for each resource type.

Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

- Fixes #2409

2021-05-26 20:27 UTC, xtreme-vikram-yadav requested changes
This is an amazing new feature. Thank you for bringing it in.

2021-05-27 20:07 UTC, mklanjsek commented on internal/objectstatus/deployment.go
> +func getSelector(deployment *appsv1.Deployment) component.Component {
Great point, thanks. Refactored to make it behave same way.

2021-05-27 20:07 UTC, mklanjsek commented on internal/objectstatus/pod.go
> +				status.Properties = append(status.Properties, component.Property{Label: "Controlled By", Value: controlledBy})
✅

2021-05-27 20:08 UTC, mklanjsek commented on internal/objectstatus/pod.go
> +			status.Properties = append(status.Properties, component.Property{Label: "Node", Value: nodeLink})
✅

2021-05-27 20:08 UTC, mklanjsek commented
@xtreme-vikram-yadav PTAL

2021-05-30 20:58 UTC, xtreme-vikram-yadav approved these changes

2021-05-31 19:07 UTC, xtreme-vikram-yadav commented
Please squash the commits before merging.

2021-06-01 14:17 UTC, merged