Create streaming interface for client streaming.
vmware-tanzu/octant pull request #2504
Opened 2021-05-28 16:31 UTC by wwitzel3

**What this PR does / why we need it**:
Extracts the current websocket streaming in to an interface that can be replaced.
This work was done by @mstergianis in #1905 this PR is just addressing the merge conflict.

2021-06-04 14:48 UTC, jamieklassen requested changes
requesting one change so that library consumers can effectively use this handy feature!

2021-06-04 14:48 UTC, jamieklassen commented on pkg/dash/dash.go
> +func WithStreamingClientFactory(factory api.StreamingClientFactory) RunnerOption {
the package `api` in this context is an `internal` package -- for library consumers to use this option the `StreamingClientFactory` type will need to be moved into a non-internal package please!

2021-06-04 16:55 UTC, mstergianis commented
@wwitzel3 happy to resolve the above two requests. I'll send you a patch

2021-06-04 17:48 UTC, mstergianis commented
@wwitzel3 in going through the exercise of resolving the requests; I realized that `StreamError` should also be part of pkg as a custom implementation should have the option to return a fatal stream error. Wanted to get your thoughts on moving this much implementation out of `internal` before I spend more time on it.

2021-06-07 21:49 UTC, GuessWhoSamFoo commented
Making `StreamError` public is fine - realistically this is only going to be consumed internally by folks at VMware.

Eventually, `internal/errors` should be public as well and can have a similar API to `pkg/store` so third party usage or tools can add warnings/errors that will be visible by UI.

2021-06-09 19:39 UTC, jamieklassen requested changes
I'd like to suggest that we move the generation of IDs into the connection factory itself -- it reduces the surface area of the connection factory interface and allows custom implementations (like the one I'd like to write) to manage their own IDs.

2021-06-09 19:39 UTC, jamieklassen commented on internal/api/streaming_connection_manager.go
> +	NewTemporaryConnection(uuid.UUID, http.ResponseWriter, *http.Request, *StreamingConnectionManager) (StreamingClient, context.CancelFunc, error)
```suggestion
	NewConnection(http.ResponseWriter, *http.Request, *StreamingConnectionManager, config.Dash) (StreamingClient, context.CancelFunc, error)
	NewTemporaryConnection(http.ResponseWriter, *http.Request, *StreamingConnectionManager) (StreamingClient, context.CancelFunc, error)
```

2021-06-09 19:39 UTC, jamieklassen commented on internal/api/streaming_connection_manager.go
> +	client, cancel, err := m.clientFactory.NewConnection(clientID, w, r, m, dashConfig)
```suggestion
	client, cancel, err := m.clientFactory.NewConnection(w, r, m, dashConfig)
```

2021-06-09 19:39 UTC, jamieklassen commented on internal/api/streaming_connection_manager.go
> +	client, cancel, err := m.clientFactory.NewTemporaryConnection(clientID, w, r, m)
```suggestion
	client, cancel, err := m.clientFactory.NewTemporaryConnection(w, r, m)
```

2021-06-09 19:39 UTC, jamieklassen commented on internal/api/websocket_connection_factory.go
> +) (StreamingClient, context.CancelFunc, error) {
```suggestion
func (wcf *WebsocketConnectionFactory) NewConnection(
	w http.ResponseWriter, r *http.Request, m *StreamingConnectionManager, dashConfig config.Dash,
) (StreamingClient, context.CancelFunc, error) {
 	clientID, err := uuid.NewUUID()
	if err != nil {
		return nil, nil, err
	}
```

2021-06-09 19:39 UTC, jamieklassen commented on internal/api/websocket_connection_factory.go
> +) (StreamingClient, context.CancelFunc, error) {
```suggestion
func (wcf *WebsocketConnectionFactory) NewTemporaryConnection(
	w http.ResponseWriter, r *http.Request, m *StreamingConnectionManager,
) (StreamingClient, context.CancelFunc, error) {
 	clientID, err := uuid.NewUUID()
	if err != nil {
		return nil, nil, err
	}
```

2021-06-14 17:50 UTC, mstergianis commented
Apologies, I made the changes requested above and forgot to update this thread.

I've made a PR against @wwitzel3's [branch](https://github.com/wwitzel3/octant/pull/240). The diffs ended up being quite large so I thought that the easiest way to make the change.

2021-06-22 22:44 UTC, wwitzel3 commented
replaced by #2581

2021-06-22 22:44 UTC, closed without merging